version: '3.8'

volumes:
  bankandb:

services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/usr/src/bot:rw
    environment:
      - TOKEN=${TOKEN}
      - GUILDS=${GUILDS}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD} 
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    tty: true
    depends_on:
      - db
    command: ["python3", "main.py"]
    restart: always

  db:
    image: mariadb:10.9.4-jammy
    volumes:
      - bankandb:/var/lib/mysql:rw
    ports:
      - 5000:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD} 
      - MARIADB_PASSWORD=${MARIADB_PASSWORD} 
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
    restart: always